### PR TITLE
use fixed order bag for montecarlo sims

### LINKED ISSUE #207: montecarlo sim should use old method of picking random tiles
For the sim to be most accurate (exhibit the least "noise") for every iteration both us and the opponent should draw the same tiles from the bag for each play being considered in that iteration. 

We should shuffle the bag after every iteration and establish its order as the drawing order, instead of the approach we currently use. One idea would be to just make a new bag type to be used only for sims that can do this.

### PR DESCRIPTION
**Pull request by domino14**
closes #207

### CODE REVIEW

File: alphabet/bag_test.go [hunk 1]
```diff
@@ -124,3 +125,20 @@ func TestRemoveTiles(t *testing.T) {
...
+	bag := NewBag(ld, ld.alph)
+	sort.Slice(bag.tiles, func(i, j int) bool { return bag.tiles[i] > bag.tiles[j] })
+
+	bag.SetFixedOrder(true)
+	is.Equal(len(bag.tiles), 100)
+	ml := make([]MachineLetter, 17)
+	err = bag.Draw(17, ml)
+	is.NoErr(err)
+
+	is.Equal(ml, []MachineLetter{3, 3, 3, 3, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0})
```
Comment (andy-k) [inline alphabet/bag_test.go:143]: any idea why it's drawing 4 D, 2 C, 2 B, 9 A, instead of from the back (3 T, 4 U, 2 V, 2 W, 1 X, 2 Y, 1 Z, 2 ?)?

Comment (domino14) [reply alphabet/bag_test.go:143]: my sort function right above flips the lessthan condition

File: alphabet/bag.go [hunk 2]
```diff
@@ -107,7 +120,9 @@ func (b *Bag) PutBack(letters []MachineLetter) {
 	for _, ml := range letters {
 		b.tileMap[ml]++
 	}
-	b.Shuffle()
+	if b.fixedOrder {
+		b.Shuffle()
+	}
```
[the remark this answers is not in the document]
Comment (domino14) [reply alphabet/bag.go:125]: we want to shuffle only if we are drawing from a bag in "fixed" order, that is either front to back or back to front on the tiles slice. We can shuffle in the other case too, but it's immaterial - shuffling doesn't really do anything since we draw from the bag randomly.
