### PR TITLE
fix #300 elitebot tiebreak

### LINKED ISSUE #300: EliteBot tiebreaking when win% is very low still not working as expected
https://woogles.io/game/AUkJNbxe?turn=21 

BestBot fails to play the bingo and proceeds to lose by 300

### PR DESCRIPTION
**Pull request by domino14**

### CODE REVIEW

File: montecarlo/stopping_condition.go [hunk 1]
```diff
@@ -99,13 +99,34 @@ func (s *Simmer) shouldStop(iterationCount uint64,
...
 		tiebreakByEquity = true
 	}
+	tentativeWinner.RUnlock()
 
 	if tiebreakByEquity {
+		// We may need to re-determine the tentative winner.
+		highestEquity := -1000000.0
+		highestEquityIdx := -1
+		for idx, p := range c {
+			p.RLock()
```
Comment (andy-k) [inline montecarlo/stopping_condition.go:109]: does this work, or should `p.RLock()` be `c[idx].RLock()`?

Comment (domino14) [reply montecarlo/stopping_condition.go:109]: `p` is a pointer in this case. maybe `c[idx].RLock()` reads better anyway
